### ISSUE TITLE
Notification has incorrect blueprint name after Commit

### ISSUE THREAD

**Issue by jgiardino** [weldr/welder-web#292] opened 2018-07-10 20:40 UTC
### Description of problem
Text displays the wrong blueprint name in the success notification that displays after submitting changes in the Pending Changes dialog 

### Component (web, API, etc)
web

### Steps to Reproduce

1. Open the edit page for a blueprint
2. Make one or more changes
3. Click Commit button in the upper right corner
4. Click Commit button on the dialog

### Actual results
The blueprint name that displays in the toast notification is incorrect:
![image](https://user-images.githubusercontent.com/21063328/42536286-9438a042-845f-11e8-9d45-766b80a83082.png)

### Expected results
The name of the current blueprint page should display instead.

**Comment by andreasn** [comment] 2018-07-24 11:57
I'm unable to reproduce this one. Did you do anything specific before running into this one?

**Comment by jgiardino** [comment] 2018-07-24 17:00
I can't reproduce this one anymore either.

**Comment by andreasn** [comment] 2018-07-24 20:18
Let's close it for now.

**Closed by andreasn** 2018-07-24 20:18 UTC
Labels: blueprint crud
