### ISSUE TITLE
welder-web strips unknown blueprint fields

### ISSUE THREAD

**Issue by bcl** [weldr/welder-web#337] opened 2018-08-15 22:56 UTC
### Description of problem
There are several blueprint sections that the UI does not yet support (eg. groups, customizations.*), if a blueprint is created with these from the cmdline or shipped with lorax-composer and it is then edited using the UI it will lose all of the fields that the UI doesn't know about. It should preserve them instead of removing them.

http://weldr.io/lorax/lorax-composer/lorax-composer.html

### Component (web, API, etc)
lorax-composer-19.7.21-2
cockpit-composer-0.1.2-1

**Comment by jgiardino** [comment] 2018-09-06 20:47
@bcl Do you have any documentation on what should be provided with [`POST /api/v0/blueprints/new`](http://weldr.io/lorax/lorax-composer/pylorax.api.html#post-api-v0-blueprints-new)?

**Comment by larskarlitski** [comment] 2018-09-11 18:11
I cannot reproduce this and the code looks like it's passing through everything that it gets from `blueprints/info`. However, the UI caches it pretty aggressively. Did you push a new version of an existing blueprint while the page was open?

Could you please provide steps to reproduce?

**Comment by bcl** [comment] 2018-09-11 18:28
AH! Yes, that appears to have been the issue. I tried to reproduce it by making a new recipe with [[customizations]] and pushing it from the cmdline, then using the UI to add a package. examining the result on the cmdline confirms that it is not stripping things and the new package was added and version number bumped as expected.

I *did* have to refresh the recipe page to get the new recipe to appear, but other than that it seems to be working as expected.

**Comment by larskarlitski** [comment] 2018-09-11 18:32
Thanks for trying again. I agree that this can be quite confusing.

In Cockpit, we try to make the UI be reactive to any state changes on the system. This is a bit further out for weldr-web, as we would need some kind of events API in the backend for that, which is probably not trivial to implement.

Hope it's ok if I close this bug for now.

**Comment by jgiardino** [comment] 2018-09-12 00:53
I'm still looking into this one. This was kind of fixed with updates made in #330 when saving a blueprint, but not completely. If you navigate to the Blueprint page > Details tab, and click the Edit button, then these details are stripped out. But in addition to that, there is some odd behavior with the name getting cached and overwriting the name of the next blueprint.

**Closed** 2018-09-15 09:52 UTC
Labels: priority-1
