### ISSUE TITLE
Repeating arrows in component details breadcrumb

### ISSUE THREAD

**Issue by jgiardino** [weldr/welder-web#253] opened 2018-06-28 01:45 UTC
The example below shows multiple breadcrumb arrows, which is incorrect. Currently, the arrows should only show as expected in a breadcrumb, as you drill down through the dependencies list.

![screenshot from 2018-06-28 00-29-55](https://user-images.githubusercontent.com/209895/42003184-6eec22cc-7a6a-11e8-834b-afe638a86d83.png)

**Comment by jgiardino** [comment] 2018-06-28 01:47
@andreasn I grabbed this from one of your comments in a PR. I'm not able to reproduce this in my Centos VM. Can you provide details about your set up? Does this issue always happen for you?

**Comment by andreasn** [comment] 2018-06-28 10:12
I haven't seen it again, so it might have been a temporary glitch.

**Comment by andreasn** [comment] 2018-06-28 12:42
I just ran into it again.

![screenshot from 2018-06-28 14-39-59](https://user-images.githubusercontent.com/209895/42034715-2db3fa24-7ae1-11e8-8951-2ddff9755e23.png)

My setup is [this script](https://gist.github.com/stefwalter/7a3460f88eb8e0ae1a95becc8006a8be) running on top of the RHEL test vm from the [Cockpit tree](https://github.com/cockpit-project/cockpit/tree/master/bots).

See the file itself for how to run it on top of a Linux system. Not sure how to execute it on a mac though :/

**Comment by jgiardino** [comment] 2018-06-28 13:36
Thanks!

**Comment by KKoukiou** [comment] 2019-04-25 12:55
@jgiardino I can't reproduce this. I suggest to close it and if we are able  to show a straightforward reproducer we can open it again.

**Closed** 2019-04-26 16:08 UTC
