### ISSUE TITLE
No feedback if I input a string that doesn't match anything in the filter

### ISSUE THREAD

**Issue by andreasn** [weldr/welder-web#261] opened 2018-06-28 13:13 UTC
### Description of problem
I was searching for the package **gnome-photos** to add to my build, but apparently that package isn't packaged in my current OS (RHEL). There is no feedback that it couldn't match the string though, so it makes me think that maybe something broke with the UI.

### Component (web, API, etc)
Web

### Version or commit hash (if applicable)
0.1.0

### How often reproducible
Always

### Steps to Reproduce

1.  Hit **Edit Blueprint**
2. Under Available Components, search for **gnome-photos**
3. Try to hit enter to do the search

### Actual results

Nothing happens when I hit the return key

### Expected results

I would expect it to give me some hint that the string didn't match anything. Maybe the input box could turn red.
![screenshot from 2018-06-28 15-13-41](https://user-images.githubusercontent.com/209895/42036455-ded41a92-7ae5-11e8-93e9-4dd6bf4c0090.png)

**Comment by jgiardino** [comment] 2018-06-28 13:17
I'm closing this as a duplicate of #249

**Comment by andreasn** [comment] 2018-06-28 13:18
Hups, sorry for the duplicate. Didn't realize it had been captured already. Thanks!

**Closed by jgiardino** 2018-06-28 13:17 UTC
